[package]
name = "posta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.4.1"
native-tls = "0.2.8"
mailparse = "0.13.7"
clap = {version = "~2.33.3", features = ["yaml"]}
